### ISSUE TITLE
Pin tasks

### ISSUE THREAD

**Issue by jjw24** [chrisnicholas90/Wox.Plugin.Todos#1]
Originally posted here by @DRYN07: https://github.com/jjw24/Wox.Plugin.Todos/issues/4

"Is it possible to pin the task to the top globally? I would like to see the task every time I open flow launcer. This would be very helpful."

**Comment by jjw24** [comment]
Flow currently doesn't have the mechanism to display results(tasks) on startup.

Next best change would be to allow plugin to pin an ordered task list that displays when its action hotkey is triggered.

**Comment by Or1g3n** [comment]
Pin feature was just released in 3.0.5:
- Added pin ( -p ) and unpin ( -p --u ) capabilities allowing user to pin todo items to top of list results
    - Pinned items will show in list results with 📌 prepended to Title to indicate item is pinned
    - Pinned items always take precedence regardless of sort option (i.e., always show at the top)
- Updated sort logic to enforce sort order (i.e., bypasses Flow Launchers built in ranking system so sort order is always maintained)

Marking issue as closed.
